---
title: "Alpha_SHUVOmilk"
author: "Chiara Gini"
date: "10/10/2022"
output: html_document
---

```{r setup, include=FALSE}
library("DT")
library("knitr")
library("dplyr")
library("tidyr")
library("broom")
library("vegan")
library("scales")
library("stringr")
library("ggplot2")
#library("ggpubr")
# library("madbito")
library("reshape2")
library("gghighlight")
library("data.table")
library("rmarkdown")
library("ggrepel")
library("tibble")
library("ggplot2")
library("tidyverse")
library("ggpubr")
```

## Alpha diversity of SKINSWABs samples

```{r}
project_folder = "/home/mycelium/Results/SHUVO-MILK/"
analysis_folder = "results/"
fname = file.path(project_folder, "mapping_shuvo_milk.csv")

metadata <- fread(fname)
metadata$sample <- "sample-"
metadata$sample<- paste(metadata$`sample-id`, metadata$SID, sep = "")
metadata = filter(metadata, sample != "sample-46")

fname = file.path(project_folder, analysis_folder, "alpha.csv")
alpha <- fread(fname)
alpha = select(alpha, -c(se.chao1, se.ACE))
alpha$`sample-id` <- gsub("\\.", "-", alpha$`sample-id`)

mAlpha <- reshape2::melt(alpha, id.vars = "sample-id", variable.name = "metric", value.name = "value")
mAlpha$type <- metadata$sample_type[match(mAlpha$`sample-id`,metadata$sample)]
mAlpha$Unit <- metadata$Unit[match(mAlpha$`sample-id`,metadata$sample)]
```

## Averages and plots

```{r pressure, echo=FALSE}
mAlpha$type = factor(mAlpha$type, levels = c("Healthy quarter", "Subclinical quarter", "Farm bulk milk"))

D <- mAlpha %>%
  group_by(metric,type, Unit) %>%
  summarize(N=n(),avg=round(mean(value),3)) %>%
  spread(key = metric, value = avg)

mAlpha$type = factor(mAlpha$type, levels = c("Healthy quarter", "Subclinical quarter", "Farm bulk milk"))

d_alpha <- D %>%
  gather(key = "metric", value = "value", -c(type, Unit,N)) %>%
  spread(key = "Unit", value = "value")

kable(D)
```

### Boxplots of alpha diversity indexes

#### Treatment by region

```{r, echo=FALSE, fig.height=12, fig.width=12}
mAlpha <- mAlpha %>% group_by(metric) %>%
  mutate(scaled_value = rescale(value, to = c(0,100)))
  
p <- ggplot(mAlpha, aes(x=type,y=scaled_value)) 
p <- p + geom_boxplot(aes(fill=Unit))
p <- p + scale_fill_manual(values=c("#56B4E9", "#E69F00"))
p <- p + facet_wrap(~metric, scales = "free")
p <- p + xlab("sample_type")
p = p + theme(strip.text = element_text(size = 12),
              axis.text.x = element_text(size = 8))
p
```

## Testing for significance

### type

```{r test_alpha, echo=FALSE}
D <- mAlpha %>%
  group_by(metric) %>%
  do(tidy(lm(value ~ type, data = .))) %>%
  filter(term != "(Intercept)")

datatable(D, options = list(pageLength=100)) %>% 
  formatStyle('p.value', backgroundColor = styleInterval(0.05, c('yellow', 'white')))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
p <- ggplot(data = D, mapping= aes(x=term, y=p.value))
p <- p + geom_point(aes(color = metric, stroke = 1), position=position_jitter(h=0, w=0.27)) #,shape=metric
p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p <- p + geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.5)
p <- p + geom_hline(yintercept=0.10, linetype="dashed", color = "darkorange", size=0.5)
p <- p + xlab("Groups") + ylab("p-values")
p <- p + coord_trans(y="log2")
p <- p + scale_y_continuous(breaks=pretty_breaks(n=20)) 
p <- p + scale_y_continuous(breaks = c(0, 0.05, 0.10, 1)) +  theme(axis.text.x = element_text(angle=0))

p
```

### unit

```{r test_alpha, echo=FALSE}
D <- mAlpha %>%
  group_by(metric) %>%
  do(tidy(lm(value ~ Unit, data = .))) %>%
  filter(term != "(Intercept)")

datatable(D, options = list(pageLength=100)) %>% 
  formatStyle('p.value', backgroundColor = styleInterval(0.05, c('yellow', 'white')))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
q <- ggplot(data = D, mapping= aes(x=term, y=p.value))
q <- q + geom_point(aes(color = metric, stroke = 1), position=position_jitter(h=0, w=0.27)) #,shape=metric
q <- q + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
q <- q + geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.5)
q <- q + geom_hline(yintercept=0.10, linetype="dashed", color = "darkorange", size=0.5)
q <- q + xlab("Units") + ylab("p-values")
q <- q + coord_trans(y="log2")
q <- q + scale_y_continuous(breaks=pretty_breaks(n=20)) 
q <- q + scale_y_continuous(breaks = c(0, 0.05, 0.10, 1)) +  theme(axis.text.x = element_text(angle=0))

q
```

```{r}
figure_finalA <- ggarrange(p, q, widths=c(1,1), heights=c(1,1),  labels=c("A", "B"), ncol=2, nrow=1 )
print(figure_finalA)

ggsave(filename = "~/Results/SHUVO-MILK/results/alpha.png", width = 12, height = 3, plot = figure_finalA, device = "png")
```


