---
title: "Alpha bootstrapping and clustering Skinswabs"
author: "Chiara Gini"
date: "02/02/2023"
output: html_document
---

```{r setup, include=FALSE}
library("DT")
library("knitr")
library("dplyr")
library("tidyr")
library("broom")
library("vegan")
library("scales")
library("stringr")
library("ggplot2")
#library("ggpubr")
# library("madbito")
library("reshape2")
library("gghighlight")
library("data.table")
library("rmarkdown")
library("ggrepel")
library("tibble")
library("ggplot2")
library("tidyverse")
library("ggpubr")
```


```{r metadata}
project_folder = "/home/mycelium/Results/Milkqua_skinswab_bootstrapping"
analysis_folder = "results/"
fname = file.path(project_folder, "mapping_milkqua_skinswabs_boot.csv")

metadata <- fread(fname)
metadata = filter(metadata, `sample-id` != "sample-29")
before_oil = filter(metadata, timepoint == "before_oil")
before_oil$treatment <- "Control"
metadata = filter(metadata, timepoint != "before_oil")
metadata = filter(metadata, treatment != "Treated")
metadata <- rbind(metadata, before_oil)
metadata$treatment <- NULL
metadata <- tibble::rownames_to_column(metadata, "sample")

metadata$timepoint[metadata$timepoint == "before_oil" ] <- "T0" 
metadata$timepoint[metadata$timepoint == "after_oil" ] <- "T1" 
metadata$timepoint[metadata$timepoint == "8" ] <- "T2" 
```


```{r clustering}
matrice= read.table("/home/mycelium/Results/Milkqua_skinswab_bootstrapping/results/bray_curtis_distances.csv", row.names = 1, header=T, sep = ",")
metadata$`sample-id` <- gsub("sample-","sample.", metadata$`sample-id`)

vec <- filter(metadata, sample_type == "skinswab") %>% select("sample-id") %>% pull()
vex <- names(matrice) %in% vec
mat_milk = matrice[vex,vex]
mat_milk$timepoint <- as.character(metadata$timepoint[match(row.names(mat_milk),metadata$`sample-id`)])

matx= data.matrix(select(mat_milk, -c(timepoint)))

## MDS
mds <- cmdscale(as.dist(matx))
mds <- cmdscale(as.dist(matx))
mds <- as.data.frame(mds)

metadata$`sample-id` <- gsub("sample.","sample-", metadata$`sample-id`)


mds$timepoint <- metadata$timepoint[match(rownames(mds), metadata$`sample-id`)]
mds$sample <- metadata$`sample-id`[match(rownames(mds), metadata$`sample-id`)]

p <- ggplot(mds, aes(V1,V2)) + geom_point(aes(colour = timepoint), size = 3) + stat_ellipse(aes(x=V1, y=V2,color=timepoint), type="norm")
p <- p + xlab("dim1") + ylab("dim2")
p

fname = file.path("~/Results/Milkqua_skinswab_bootstrapping/results/beta/beta_clustering.png")
ggsave(filename = fname, plot = p, device = "png", dpi = 300, width = 10, height = 7)
```




```{r alpha}
fname = file.path(project_folder, analysis_folder, "alpha.csv")
alpha <- fread(fname)
alpha = select(alpha, -c(se.chao1, se.ACE))
names(alpha)[1] <- "sample-id"
alpha$`sample-id` <- gsub("\\.", "-", alpha$`sample-id`)

mAlpha <- reshape2::melt(alpha, id.vars = "sample-id", variable.name = "metric", value.name = "value")
mAlpha$timepoint <- metadata$timepoint[match(mAlpha$`sample-id`,metadata$`sample-id`)]
# mAlpha$timepoint[mAlpha$timepoint == "before_oil" ] <- "T0" 
# mAlpha$timepoint[mAlpha$timepoint == "after_oil" ] <- "T1" 
# mAlpha$timepoint[mAlpha$timepoint == "8" ] <- "T2" 

C <- mAlpha %>%
  group_by(metric, timepoint) %>%
  summarize(N=n(),avg=round(mean(value),3)) %>%
  spread(key = metric, value = avg)
write.csv(C, file="~/Results/Milkqua_skinswab_bootstrapping/results/alpha/alpha_base.csv")

D <- mAlpha %>%
  group_by(metric) %>%
  do(tidy(lm(value ~ timepoint, data = .))) %>%
  filter(term != "(Intercept)")

datatable(D, options = list(pageLength=100)) %>% 
  formatStyle('p.value', backgroundColor = styleInterval(0.05, c('yellow', 'white')))

mAlpha <- mAlpha %>% group_by(metric) %>%
  mutate(scaled_value = rescale(value, to = c(0,100)))
```

```{r alpha plot base, echo=FALSE, message=FALSE, warning=FALSE}
p <- ggplot(data = D, mapping= aes(x=term, y=p.value))
p <- p + geom_point(aes(color = metric, stroke = 1), position=position_jitter(h=0, w=0.27)) #,shape=metric
p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p <- p + geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.5)
p <- p + geom_hline(yintercept=0.10, linetype="dashed", color = "darkorange", size=0.5)
p <- p + coord_trans(y="log2")
p <- p + scale_y_continuous(breaks=pretty_breaks(n=20)) 
p <- p + scale_y_continuous(breaks = c(0, 0.05, 0.10, 1)) +  theme(axis.text.x = element_text(angle=90))
#p <- p + scale_color_manual(values = c("#f8766d", "#d39200", "#93aa00", "#00ba38", "#00c19f", "#00b9e3", "#619cff", "#db72fb", "#ff61c3"))
p

ggsave(filename = "~/Results/Milkqua_skinswab_bootstrapping/results/alpha/scatterplot_alpha_base.png", width = 6, height = 4, plot = p, device = "png")
```

## Bootstrapping

```{r alpha bootstrapping}
boot_sample = function(data,index) {
  n = nrow(data)
  vec = sample(1:n, n, replace = TRUE)
  temp = data[vec,]
  return(temp)
}
```

```{r, echo=FALSE}
indices <- colnames(alpha)[-1]

res = data.frame("index"=NULL, "stat"=NULL, "pval"=NULL, "coef"=NULL, "timepoint"=NULL)

for (k in indices) {
  mm = mAlpha[mAlpha$metric == k,]
    for (i in 1:10000) {
    print(paste("bootstrap replicate n.", i))
    temp = boot_sample(mm, k)
    
      tbl = temp %>%
      group_by(timepoint) %>%
      summarise(N=n()) %>%
      spread(key = timepoint, value = N)
      
     tmp <- temp %>%
      group_by(metric) %>%
      do(tidy(lm(scaled_value ~ timepoint, data = .))) %>%
      filter(term != "(Intercept)") 
 
    res = bind_rows(res, tmp)
  }   # bootstrap replicates
} # indices

write.csv(res, "~/Results/Milkqua_skinswab_bootstrapping/results/alpha/Bootstrap_10000replicates_7indicesTEST.csv")
```

```{r}
res <- fread("~/Results/Milkqua_skinswab_bootstrapping/results/alpha/Bootstrap_10000replicates_7indicesTEST.csv")

s <- ggplot(data = res, mapping= aes(x=metric, y=p.value)) + geom_boxplot(aes(fill=metric))
s <- s + facet_wrap(~term) + theme(axis.text.x = element_text(angle=90))
s
#ggsave(filename = "~/Results/SKINSWABS/results/bootstrapping_1000replicates_7indices_boxplot.png", width = 10, height = 5, plot = p, device = "png")
```

```{r}
r <- ggplot(res, aes(metric, p.value, group = term)) +
  geom_smooth(aes(color = term), method = loess, size = 0.7, alpha = 0.15) +
  theme_light(base_size = 16) + theme(axis.text.x = element_text(angle=90))

r
```

```{r}
D = res %>%
  group_by(term, metric) %>%
  summarise(avg = median(p.value), std = sd(p.value), wt = 1/std)

px <- ggplot(data = D, mapping= aes(x=term, y=avg))
px <- px + geom_point(aes(color = metric, size = wt), position=position_jitter(h=0, w=0.27))
px <- px + geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.5)
px <- px + geom_hline(yintercept=0.10, linetype="dashed", color = "darkorange", size=0.5)
px <- px + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
px <- px + coord_trans(y="log2")
px <- px + scale_y_continuous(breaks=pretty_breaks(n=20)) 
px <- px + scale_color_manual(values = c("#f8766d", "#d39200", "#93aa00", "#00ba38", "#00c19f", "#00b9e3", "#619cff", "#db72fb", "#ff61c3"))
px <- px + scale_shape_manual(values = c(0, 1, 2, 23, 3,4,7, 8, 10))
# px <- px + gghighlight(avg < 0.10, label_key = metric, use_direct_label = TRUE)
px <- px +  theme(legend.key.size = unit(0.05, 'cm'), axis.text.x = element_text(angle=90))
px <- px+ scale_y_continuous(breaks = c(0, 0.05, 0.10, 1))
px
# ggsave(filename = "~/Results/Milkqua_skinswab_bootstrapping/results/alpha_Bootstrap_10000replicates_7indices.png", width = 5, height = 5, plot = px, device = "png")
```
`
```{r}
part1  <- ggarrange(p, px, widths=c(1, 1), heights=c(1, 1),  labels=c("A", "B"), nrow=1, ncol=2)
part2 <- ggarrange(part1, s, widths=c(1, 1), heights=c(1, 1),  labels=c("", "C"), nrow=2, ncol=1)
ggsave(filename = "~/Results/Milkqua_skinswab_bootstrapping/results/alpha_Bootstrap_2_10000replicates_7indices.png", width = 12, height = 12, plot = part2, device = "png")
```

## grafico boostrapping

```{r, echo=FALSE, message=FALSE, warning=FALSE}
p2 <- ggplot(data = res, mapping= aes(x=term, y=p.value))
p2 <- p2 + geom_point(aes(color = metric, stroke = 1, shape = metric), position=position_jitter(h=0, w=0.27))
p2 <- p2 + geom_hline(yintercept=0.05, linetype="dashed", color = "red", size=0.5)
p2 <- p2 + geom_hline(yintercept=0.10, linetype="dashed", color = "darkorange", size=0.5)
p2 <- p2 + scale_y_continuous(breaks=pretty_breaks(n=20)) 
p2 <- p2 + scale_color_manual(values = c("#ff61c3")) 
p2 <- p2 + scale_shape_manual(values = c(10))
#p2 <- p2 + gghighlight(p.value < 0.10, label_key = metric, use_direct_label = FALSE)
p2 <- p2 +  theme(legend.key.size = unit(0.05, 'cm'))
p2 <- p2 + coord_trans(y="log2")
p2

#Fisher <- p2

#print(Fisher)

#ggsave(filename = "~/Results/SKINSWABS/results/alpha_significance_tablewithdots_TIMEPOINT_correctedforbaseline_Skinswabs_Fisher.png", width = 6, height = 8, plot = p2, device = "png")
```


### aggiungere tabellina per contare quanti indici sono sotto soglia tra i due timepoint

```{r}
R <- res %>%
  group_by(term) %>%
  filter(p.value<0.05) 

table(R['term'])

```
