---
title: "pipeline-comparison-1-CND-debugging"
author: "Chiara Gini"
date: "2023-09-13"
output: html_document
---

```{r packages, include=FALSE}
library(data.table)
library(tidyverse)
library(scales) #used for rescale
```


```{r setup general, include=FALSE}
project_folder = "/home/mycelium/Results/PIPELINE_COMPARISON/RESULTS"
analysis_folder = "reprogram-debug2/" #others will be 99_milkdataset & 99_mockrobiota
base_dir <- file.path(project_folder, analysis_folder)
```


```{r setup Vsearch, include=FALSE}
VS = data_frame()
all_files_VS <- paste0(base_dir, list.files(base_dir, recursive = TRUE, pattern = "Vsearch"))
for (filename in all_files_VS) {
  show(filename)
  tmp <- fread(filename)
  tmp$file <- filename
  tmp$OTU_ID <- as.character(tmp$`#OTU_ID`)
  VS = bind_rows(VS, tmp)
}

# VS$V2 <- NULL 
# names(VS) <- gsub(x = names(VS), pattern = "_R1", replacement = "")
# VS <- subset(VS, select = -1)
VS$file <- str_remove(VS$file, "/home/mycelium/Results/PIPELINE_COMPARISON/RESULTS/reprogram-debug2/otu_table-") #change here
VS$file <- str_remove(VS$file, ".csv") #change here
VS <- VS %>% separate(file, c('pipeline', 'database'), sep = "_x_")
# VS <- subset(VS, select = c(1:73)) #dedicated to the milk dataset
VS$species <- NULL
names(VS) <- gsub(x = names(VS), pattern = "X", replacement = "sample")
VS$kingdom <- str_remove(VS$kingdom, "k__") #change here
VS$phylum <- str_remove(VS$phylum, "p__") #change here
VS$class <- str_remove(VS$class, "c__")
VS$order <- str_remove(VS$order, "o__")
VS$family <- str_remove(VS$family, "f__")
VS$genus <- str_remove(VS$genus, "g__")
VS$OTU_ID <- NULL
VS$`#OTU_ID` <- NULL
```


```{r setup Qiime2, include=FALSE}
Q2 = data_frame()
all_files_Q2 <- paste0(base_dir, list.files(base_dir, recursive = TRUE, pattern = "Qiime2"))
for (filename in all_files_Q2) {
  show(filename)
  tmp <- fread(filename)#, skip = 1)
  tmp$file <- filename
  Q2 = bind_rows(Q2, tmp)
}

# names(Q2) <- Q2[1,]
# Q2 <- Q2[-1,]
# colnames(Q2)[11] <- "file"

Q2$file <- str_remove(Q2$file, "/home/mycelium/Results/PIPELINE_COMPARISON/RESULTS/reprogram-debug2/feature-table-") #change here
Q2$file <- str_remove(Q2$file, ".tsv") #change here
Q2 <- Q2 %>% separate(file, c('pipeline', 'database'), sep = "_x_")
# Q2 <- Q2 %>% separate(`#OTU ID`, c("kingdom", "phylum", "class", "order", "family", "genus"), sep = ";")
# colnames(Q2)[1] <- "kingdom"
# colnames(Q2)[2] <- "phylum"
# colnames(Q2)[3] <- "class"
# colnames(Q2)[4] <- "order"
# colnames(Q2)[5] <- "family"
# colnames(Q2)[6] <- "genus"
# colnames(Q2)[7] <- "sample50"
# colnames(Q2)[8] <- "sample51"
# colnames(Q2)[9] <- "sample52"
# colnames(Q2)[10] <- "sample53"

Q2$kingdom <- str_remove(Q2$kingdom, "k__") #change here
Q2$phylum <- str_remove(Q2$phylum, "p__") #change here
Q2$class <- str_remove(Q2$class, "c__")
Q2$order <- str_remove(Q2$order, "o__")
Q2$family <- str_remove(Q2$family, "f__")
Q2$genus <- str_remove(Q2$genus, "g__")
```


```{r setup Micca, include=FALSE}
Mi = data_frame()
all_files_Mi <- paste0(base_dir, list.files(base_dir, recursive = TRUE, pattern = "Micca"))
for (filename in all_files_Mi) {
  show(filename)
  tmp <- read.csv(filename, header = T)
  tmp$file <- filename
  Mi = bind_rows(Mi, tmp)
}

names(Mi) <- gsub(x = names(Mi), pattern = "X", replacement = "sample")
## Mi$sample <- NULL
Mi$OTU <- NULL
Mi$species <- NULL
Mi$file <- str_remove(Mi$file, "/home/mycelium/Results/PIPELINE_COMPARISON/RESULTS/reprogram-debug2/taxonomy_") #change here
Mi$file <- str_remove(Mi$file, ".csv") #change here
Mi <- Mi %>% separate(file, c('pipeline', 'database'), sep = "_x_")
Mi$kingdom <- str_remove(Mi$kingdom, "k__") #change here
Mi$phylum <- str_remove(Mi$phylum, "p__") #change here
Mi$class <- str_remove(Mi$class, "c__")
Mi$order <- str_remove(Mi$order, "o__")
Mi$family <- str_remove(Mi$family, "f__")
Mi$genus <- str_remove(Mi$genus, "g__")
Mi$sample <- NULL
```


```{r setup Qiime1.9, include=FALSE}
Q1_9 = data_frame()
all_files_Q1_9 <- paste0(base_dir, list.files(base_dir, recursive = TRUE, pattern = "Qiime1.9"))
for (filename in all_files_Q1_9) {
  show(filename)
  tmp <- fread(filename) #, skip = 1)
  tmp$file <- filename
  tmp$`#OTU_ID` <- as.character(tmp$`#OTU_ID`)
  Q1_9 = bind_rows(Q1_9, tmp)
}

Q1_9$`#OTU_ID` <- NULL
# names(Q1_9) <- gsub(x = names(Q1_9), pattern = "cutadapt", replacement = "")
Q1_9$file <- str_remove(Q1_9$file, "/home/mycelium/Results/PIPELINE_COMPARISON/RESULTS/reprogram-debug2/otu_table_") #filtered_") if milkdataset, else change 
Q1_9$file <- str_remove(Q1_9$file, ".tsv") #change here
Q1_9 <- Q1_9 %>% separate(file, c('pipeline', 'database'), sep = "_x_")
# Q1_9 <- Q1_9 %>% separate(taxonomy, c("kingdom", "phylum", "class", "order", "family", "genus"), sep = ";")
Q1_9$kingdom <- str_remove(Q1_9$kingdom, "k__") #change here
Q1_9$phylum <- str_remove(Q1_9$phylum, "p__") #change here
Q1_9$class <- str_remove(Q1_9$class, "c__")
Q1_9$order <- str_remove(Q1_9$order, "o__")
Q1_9$family <- str_remove(Q1_9$family, "f__")
Q1_9$genus <- str_remove(Q1_9$genus, "g__")
Q1_9$species <- NULL
Q1_9$`#OTU ID` <- NULL
```

```{r taxonomic df, include=FALSE}
res = data_frame()
res <- rbind(Mi, Q1_9, Q2, VS)
res <- filter(res, phylum != "Plantae")
res <- filter(res, family !="Mitochondria")
res <- filter(res, class !="Chloroplast")

phyla <- subset(res, select=-c(kingdom, class, order,family, genus))
#genera <- subset(res, select=-c(kingdom, phylum, class, order, family))

phyla$phylum <- sub ("^$", "Undefined", phyla$phylum)
phyla$phylum <- sub ("NA", "Undefined", phyla$phylum)
phyla$phylum <- sub ("__", "Undefined", phyla$phylum)
phyla$tot <- rowSums(phyla[,c(1:4)],)
phyla$info <- paste(phyla$phylum, phyla$pipeline, phyla$database, sep = ";")
phyla <- subset(phyla, select = c(tot, info))
phyla <- phyla %>%
  group_by(info) %>%
  summarise(across(everything(), sum))

phyla <- phyla %>% separate(info, c("phylum", "pipeline", "database"), sep = ";")
```

```{r testing the cleaning}
test1 <- split(phyla, with(phyla, interaction(pipeline, database)), drop = TRUE)
res = data.frame()

 for (i in test1) {
   title <- paste(i$pipeline, i$database, sep = ";")
    D <- i %>%
       group_by(phylum) %>%
       summarise(N=n(), avg_abund = round(mean(tot),6), std = round(sd(tot),3)) %>%
       filter(avg_abund>5) %>% #Filter here
       arrange(phylum,avg_abund)
    G <- D %>%
      group_by(phylum) %>%
      summarize("s"=sum(avg_abund)) %>%
      arrange(desc(s)) %>%
      dplyr::select(phylum,s)
  
    D$phylum <- factor(D$phylum, levels = rev(G$phylum[order(G$s)]))
    D <- D %>%
      arrange(phylum)
    D$rescale <- D$avg_abund/sum(D$avg_abund)*100

  res = bind_rows(res, D)
  }
  

  
     # i$tot <- i$tot/colSums(i$tot)
   dataframeMicca.16SITGDB$xy <- dataframeMicca.16SITGDB$tot/sum(dataframeMicca.16SITGDB$tot)
 # i$info <- paste(i$phylum, i$pipeline, i$database, sep = ";")
 # subset(i, select = -c(phylum, pipeline, database))
 # i <- i  %>% 
 #   group_by(info) %>%
 #   summarise(across(everything(), sum))

  }


purrr::iwalk(
  .x = test1,
  .f = function(x, y) {
    x <- as.data.frame(x)
    y <- paste0('dataframe', y)
    assign(y, x, envir = globalenv())
  }
)


# test2 <- test1$Micca.16SITGDB
# test2$info <- paste(test2$phylum, test2$pipeline, test2$database, sep = ";")
# temp2 <- subset(test2, select = -c(phylum, pipeline, database))
# temp2 <- temp2 %>%
#   group_by(info) %>%
#   summarise(across(everything(), sum))
# temp2a <- subset(temp2, select = -c(info))
temp2a <- temp2a/colSums(temp2a)
temp2a$tot <- rowSums(temp2a)
temp2a <- cbind(temp2a, temp2$info)

D <- dataframeMicca.16SITGDB %>%
  group_by(phylum) %>%
  summarise(N=n(), avg_abund = round(mean(tot),6), std = round(sd(tot),3)) %>%
  filter(avg_abund>0.10) %>% #Filter here
  arrange(phylum,avg_abund)

G <- D %>%
  group_by(phylum) %>%
  summarize("s"=sum(avg_abund)) %>%
  arrange(desc(s)) %>%
  dplyr::select(phylum,s)

D$phylum <- factor(D$phylum, levels = rev(G$phylum[order(G$s)]))
D <- D %>%
  arrange(phylum)
D$rescale <- D$avg_abund/sum(D$avg_abund)*100 
```

```{r phyla}
phyla$phylum <- sub ("^$", "Undefined", phyla$phylum)
phyla$phylum <- sub ("NA", "Undefined", phyla$phylum)
phyla$phylum <- sub ("__", "Undefined", phyla$phylum)
phyla$info <- paste(phyla$phylum, phyla$pipeline, phyla$database, sep = ";")
temp <- subset(phyla, select = -c(phylum, pipeline, database))
temp <- temp %>%
  group_by(info) %>%
  summarise(across(everything(), sum))
temp2 <- subset(temp, select = -c(info))
temp2 <- temp2/colSums(temp2)
temp2$tot <- rowSums(temp2) #testing if sum influencs or not
phyla <- cbind(temp2, temp$info)
#colnames(phyla)[66] <- "info" 
# colnames(phyla)[5] <-"info"
colnames(phyla)[6] <-"info"

phyla <- phyla %>% separate(info, c("phylum", "pipeline", "database"), sep = ";")
phyla <- subset(phyla, select = c(pipeline, database, tot, phylum)) #sample 1 è tot in tutte le piepline 
#phyla <- subset(phyla, select = c(pipeline, database, sample50, sample51, sample52, sample53, phylum)) #sample 1 è tot in tutte le piepline tranne mock 22
# piepercent<- round(100*x/sum(x), 1)
```

```{r phyla}
q <- ggplot(phyla, aes(x=factor(1), y= tot, fill=phylum)) +
  geom_bar(stat="identity", width=1, position = "fill") +
  coord_polar("y", start=0) +
  facet_grid(pipeline~database ) +
  theme(legend.position = "right", panel.grid = element_blank(), axis.text = element_blank()) +
  xlab("Pipelines") + ylab("Datasets")
  
ggsave(filename = file.path(project_folder, analysis_folder, "test-ofmonday.png"), plot = q, device = "png", width = 25, height = 10)
```
